game_server:
  host: <emulator_host_ip - eth0>
  path: game_servers/fbneo
  extra_args: >-
    --output-dims=320x256
    --scale=shortestxaspect
game_clients:
  - host: <screen1_host_ip - eth0>
    path: <path_to_client - should match deploy.yaml>
    srect: 0,0-320,128
    drect: 0,0-320,128
    extra_args: >-
      --led-rows=64
      --led-cols=64
      --led-chain=5
      --led-parallel=2
      --led-slowdown-gpio=4
      --led-gpio-mapping=regular
      --led-pwm-bits=6
  - host: <screen2_host_ip - eth0>
    path: <path_to_client - should match deploy.yaml>
    srect: 0,128-320,256
    drect: 0,0-320,128
    extra_args: >-
      --led-rows=64
      --led-cols=64
      --led-chain=5
      --led-parallel=2
      --led-slowdown-gpio=4
      --led-gpio-mapping=regular
      --led-pwm-bits=6
