game_server:
  host: <emulator_host_ip>
  path: rgbfbneo
game_clients:
  - host: <screen1_host_ip>
    path: rgbfbneo
    srect: 0,0-320,128
    drect: 0,0-320,128
  - host: <screen2_host_ip>
    path: rgbfbneo
    srect: 0,128-320,256
    drect: 0,0-320,128
