game_server:
  host: <game_server_eth0_ip>
  path: game_servers
  extra_args: >-
    -background
    --output-dims=320x256
    --scale-mode=shortestxaspect
game_clients:
  - host: <game_client_1_eth0_ip>
    path: rgbclient/
    exe: rgbclient
    extra_args: >-
      --retry-count=10
      --retry-delay=500
      --led-rows=64
      --led-cols=64
      --led-chain=5
      --led-parallel=2
      --led-slowdown-gpio=4
      --led-gpio-mapping=regular
      --led-pwm-bits=6
      --src-rect=0,0-320,128
      --dest-rect=0,0-320,128
      --content-rect=0,0-320,256
  - host: <game_client_2_eth0_ip>
    path: rgbclient/
    exe: rgbclient
    extra_args: >-
      --retry-count=10
      --retry-delay=500
      --led-rows=64
      --led-cols=64
      --led-chain=5
      --led-parallel=2
      --led-slowdown-gpio=4
      --led-gpio-mapping=regular
      --led-pwm-bits=6
      --src-rect=0,128-320,256
      --dest-rect=0,0-320,128
      --content-rect=0,0-320,256
